services:
  pterodroid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pterodroid
    user: "root"
    ports:
      - "3001:3001"
    volumes:
      - pterodroid_data:/home/appuser/data
      - ./data:/workspaces/pterodroid/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - pterodroid-net

  redis:
    image: redis:7-alpine
    container_name: pterodroid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - pterodroid-net

volumes:
  pterodroid_data:
    driver: local
  redis_data:
    driver: local

networks:
  pterodroid-net:
    driver: bridge
